### ISSUE TITLE
Working with very large strings

### ISSUE THREAD

**Issue by MrNeither** [robertgr991/fastDamerauLevenshtein#1]
Hello. Thank you for your project. I have one question, I hope for Your help.
I have two very large arrays of numbers (integers, from 0 to 100), I want to find out how similar these two arrays are. I thought I could translate these lists to string list, and then use Your string similarity metric. However, the size of arrays is very large (about 16,000 elements), and there is not enough memory.
Perhaps there is a way to calculate this metric approximately in order to use less memory, or maybe somehow reduce the array?
Thank you very much for any help

**Comment by robertgr991** [comment]
Hello

Have you tried computing the similarity directly with the integers arrays? Like this:
```python
print(damerauLevenshtein(arr1, arr2))
```
Maybe you get a good result. Also, what are you trying to achieve by comparing the arrays?

**Comment by MrNeither** [comment]
I didn't notice that Your code also works with arrays of integers, thank you:)

I do research some functions over finite fields. After certain transformations I get an array, for example `[3,3,3,3,...,179,179,179,...,12,12,12,12,12,...]` over GF(256). It consists of a series of identical elements, the series may meet several times and their length may be different. And for each function, the array will be its different and contain a different length (because I also consider subfields, other finite fields, and bounded functions). 

I have a hypothesis that is to find the "similarity" of function classes. I'm not sure that I can explain the essence of building classes correctly and briefly, but in General, it all comes down to this: if you need fewer transformations to reduce one array to another, then the classes are more "similar".
But functions can have a very large degree, and therefore arrays are very long. They can be compressed very much if you replace the series with a single element, but their length is still important. 
And if I run Your code on such large arrays, I get an error. 
![image](https://user-images.githubusercontent.com/42472993/80784183-d5f88780-8b84-11ea-96d5-8f2352938f16.png)
Most likely, there is not enough memory on computer

On smaller arrays(on the order of 10000) Your code works perfectly (I didn't expect this speed). I suppose it is possible to construct a cost matrix where the cost will depend on the length of the series, but I am not sure that the algorithm can be modified like this. 
Will be happy to receive any information from You :)

Sorry for my English:)

**Comment by robertgr991** [comment]
What python version are you using? Is it 32 or 64 bit? Maybe your OS is limiting how much memory python processes can use? I've tried it on two arrays of 20k elements each and I had no memory problem (Python 3.8 64 bit).

I suggest you to look into cosine similarity and tf-idf(term-frequency inverse-document-frequency), You will consider your arrays as "documents" and their elements as "words". You construct the documents matrix and then compute cosine similarity on them. It's a simple and fast algorithm and I think it can be useful in your case. Here are some links from google: 
[https://towardsdatascience.com/tf-idf-for-document-ranking-from-scratch-in-python-on-real-world-dataset-796d339a4089](https://towardsdatascience.com/tf-idf-for-document-ranking-from-scratch-in-python-on-real-world-dataset-796d339a4089) 
[https://janav.wordpress.com/2013/10/27/tf-idf-and-cosine-similarity/](https://janav.wordpress.com/2013/10/27/tf-idf-and-cosine-similarity/) 
[https://courses.cs.washington.edu/courses/cse573/12sp/lectures/17-ir.pdf](https://courses.cs.washington.edu/courses/cse573/12sp/lectures/17-ir.pdf)

Let me know how this works and if I can further help you.

**Comment by MrNeither** [comment]
Thank you very much. An interesting option, I will try it.

Yes, indeed I only have 8 GB of memory, so there is an overflow, and the system kills the process.
Thank you very much for your help.

**Comment by robertgr991** [comment]
No problem, let me know if it works and close this issue when you can. Thx.

**Comment by MrNeither** [comment]
Thank you, this really works on my data, but it's not exactly what I need. I still decided to use your code with the Levenshtein method, I just had to use a more powerful computer:)
